---
title: "R Notebook"
output: html_notebook
---

```{r,message=F}
library(data.table)
library(dplyr)
library(ggplot2)
library(cowplot)
library(patchwork)
library(rprojroot)
F = is_rstudio_project$make_fix_file() 
```


```{r}

#function to summarize
fsummarize=function(phenotype="smooth",correction="cm",grm="gonly"){
  dat = fread(F(paste("gwas/grid/genotypes/tau100/ss500/train/gwas_results/mlma/gridt100.",phenotype,".",correction,".all.",grm,".mlma.gz",sep="")))
  colnames(dat)=
    c("CHROM","ID","position","A1","A2","ALT_FREQS","BETA","SE","P")
  dat=dat[,.(ID,P,ALT_FREQS)]
  dat[ALT_FREQS<=0.5,maf:=ALT_FREQS,]
  dat[ALT_FREQS>0.5,maf:=1-ALT_FREQS,]
  dat[maf>=0.05,fcat:="common"]
  dat[maf<0.01,fcat:="rare"]
  dat[maf>=0.01 & maf<0.05,fcat:="medium"]
  
  dat = dat[fcat=="common" | fcat=="rare"]

  
  #calculating expected Pvalue distribution and lambda
  dat=dat[order(P),.SD,by="fcat"]

  dat[ , ix := 1:.N, by = fcat]
  #subsample rows
  f.subsample=function(df1){
    if(nrow(df1)>(1e5+1000)){
      step_size=floor(nrow(df1)/1e5)
      df2 = rbind(df1[c(1:1000),],
                  df1[seq(1001,nrow(df1),step_size),])
    }else{df2=df1}
    return(df2)
  }
  dat.common = f.subsample(dat[fcat == "common",])
  dat.rare = f.subsample(dat[fcat == "rare",])
  dat = rbind(dat.common,dat.rare)
  dat[,c("exp.p","obs.chi"):=list(
    ix/(max(ix)+1), 
    qchisq(P,df=1,lower.tail = FALSE)
    ), by=fcat]
  dat[,"exp.chi":=qchisq(exp.p,df=1,lower.tail = FALSE)]
  dat[,"lambda":=obs.chi/exp.chi]
  dat=dat[,chi.percentile:=1-exp.p]
  
  dat[,lower.ci:=qbeta(0.025,shape1=ix,shape2 = max(ix)-ix),by=fcat]
  dat[,upper.ci:=qbeta(0.975,shape1=ix,shape2 = max(ix)-ix),by=fcat]
  dat = dat[,.(fcat,P,ix,exp.p,obs.chi,exp.chi,lambda,chi.percentile,lower.ci,upper.ci)]
  #dat = dat[, lapply(.SD,mean), 
  #          by = .(fcat,ix)]
  
  return(dat)
}


fplot=function(dat,title="Common-LMM"){
  

  plt1<-ggplot(data=dat)+
    geom_ribbon(aes(x=-log10(exp.p),
                    ymin=-log10(lower.ci),
                    ymax=-log10(upper.ci),
                    fill=fcat),
                alpha=0.2,
                show.legend = FALSE)+
    geom_line(aes(-log10(exp.p),
                  -log10(P),
                  color=fcat),
              size=0.7,
              alpha=0.5,
              show.legend = FALSE)+
        geom_abline(intercept=0,slope=1,color="black")+
    scale_color_manual(values=c("#ff7f00","#377eb8"))+
    scale_fill_manual(values=c("#ff7f00","#377eb8"))+
    theme_bw()+
    theme(panel.grid=element_blank(),
          axis.text=element_text(size=10),
          axis.title=element_blank(),
          plot.title = element_text(hjust=0.5),
          plot.background = element_blank(),
          plot.margin = unit(rep(0.5,4), "pt"))+
    labs(color="Freq.",
         title=title)+
    xlim(c(0,max.log10P))+
    ylim(c(0,max.log10P))
  
  plt.inset=ggplot()+
    geom_line(data=dat[chi.percentile>0.999,],
              aes(chi.percentile,
                  lambda,
                  color=fcat),
              show.legend = FALSE,
              size=0.5)+
    annotate(geom="text",
             x=0.9993,
             y=0.9*max.lambda,
             label="lambda[p]",parse=TRUE)+
    theme_bw()+
    theme(panel.grid.major.x = element_blank(),
          legend.position="none",
          axis.title=element_blank(),
          panel.grid=element_blank(),
          plot.background = element_blank(),
          axis.text.x = element_text(hjust=0,size=9),
          axis.text.y = element_text(size=9))+
    scale_x_log10(limits=c(0.999,1),
                  breaks=c(0.999,1),
                  labels=c("0.999","1"),
                  position="top")+
    scale_y_continuous(limits=c(0.99, round(max.lambda,2)),
                       breaks=c(1, round(max.lambda,2)),
                       position="left")+
    labs(x="p")+
    scale_color_manual(values=c("#ff7f00","#377eb8"))
  
  plt.wt.inset<-ggdraw(plt1) +
    draw_plot(plt.inset, x=0.3, y=0.08, height=0.4,width=0.7)
  
  return(plt.wt.inset)
}
```



```{r}
dat1.grm=fsummarize("smooth","cm","gwtpcs")
dat2.grm=fsummarize("smooth","re","gwtpcs")

median.lambda=lapply(list(dat1.grm,dat2.grm),
                     function(x){
                       return(
                         x[chi.percentile>0.49 & 
                                    chi.percentile<0.51,
                                  median(lambda),by=fcat])
                     })

names(median.lambda)=c("common","rare")

median.lambda=bind_rows(median.lambda,.id="correction")
colnames(median.lambda)[3]="lambda1"

median.lambda

max.lambda=max(sapply(list(dat1.grm,dat2.grm),
                      function(x){
                        max( x[x$chi.percentile>0.999, "lambda"])
                      }))

max.log10P=max(sapply(list(dat1.grm,dat2.grm),
                      function(x){
                        max(-log10(x$P))
                      }))


plt1=fplot(dat1.grm,"Common LMM")
plt2=fplot(dat2.grm,"Rare LMM")

plt_combined.sm.gwtpcs=plt1+plt2

plt_combined.sm.gwtpcs
```

```{r}
dat1.grm=fsummarize("sharp","cm","gwtpcs")
dat2.grm=fsummarize("sharp","re","gwtpcs")

median.lambda=lapply(list(dat1.grm,dat2.grm),
                     function(x){
                       return(
                         x[chi.percentile>0.49 & 
                                    chi.percentile<0.51,
                                  median(lambda),by=fcat])
                     })

names(median.lambda)=c("common","rare")

median.lambda=bind_rows(median.lambda,.id="correction")
colnames(median.lambda)[3]="lambda1"

median.lambda

max.lambda=max(sapply(list(dat1.grm,dat2.grm),
                      function(x){
                        max( x[x$chi.percentile>0.999, "lambda"])
                      }))

max.log10P=max(sapply(list(dat1.grm,dat2.grm),
                      function(x){
                        max(-log10(x$P))
                      }))


plt1=fplot(dat1.grm,"Common LMM")
plt2=fplot(dat2.grm,"Rare LMM")

plt_combined.shp.gonly=plt1+plt2

plt_combined.shp.gonly
```


```{r}

plt_combined.both=plt_combined.sm.gwtpcs/plt_combined.shp.gonly

ggsave(F("plots/qqplots/plt_qq_mlma_t100_07132020.pdf"),
       plt_combined.both,
       height=12,
       width=14,
       units="cm")
```